kind = "mobile"
previewPath = "/mobile/"
title = "Field Engineer App"
version = "1.0.0"
id = "artifacts/mobile"
router = "path"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/mobile/" ]
localPort = 8008

[services.development]
run = "pnpm --filter @workspace/mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/mobile", "run", "serve" ]

[services.env]
PORT = "8008"
BASE_PATH = "/mobile/"
